# 站点名称
site_name: 'ResNet'
# 仓库链接
repo_url: https://github.com/zjZSTU/ResNet.git
# 作者
site_author: 'zhujian'
# 版权信息
copyright: '2020, zhujian'
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
site_dir: 'site'
# 额外信息
extra:
    # 版本号
    version: 0.1.0
# 主题
theme: 
    # name: 'readthedocs'
    # name: 'mkdocs'
    name: 'material'
# markdown扩展
markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.arithmatex

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
# 导航
nav:
    - Home: index.md
    - 数据集: dataset.md
    - ResNet:
        - 引言: './resnet/index.md'
        - 训练日志: './resnet/log-resnet_18-vs-34-vs-50.md'
    - ResNet_v2:
        - 引言: './resnet_v2/index.md'
        - 训练日志: './resnet_v2/log-resnet101_v2-vs-resnet101.md'
    - DenseNet:
        - 引言: './densenet/index.md'